version: 2.1

jobs:
  deployment:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
      - image: postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
    

    steps:
      - checkout
      - setup_remote_docker
      - run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push web --recursive
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release 

workflows:
  version: 2
  build_deploy:
    jobs:
      - deployment:
           context: docker-test
