version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  deployment:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
      - image: postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test

    
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run:
          name: Set $HEROKU_APP_NAME 
          command: |
            echo 'export HEROKU_APP_NAME=docker-ging-app$(if [ "$CIRCLE_BRANCH" != "master" ]; then echo -staging; fi)' >> $BASH_ENV
      - run: 
          command: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
          working_directory: myapp
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  version: 2
  build_deploy:
    jobs:
      - deployment:
           context: docker-test
           filters:
            branches:
              only:
                - staging
                - master        
        
